# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tools',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/tools',
                'lib_path': 'tools'},
  'syms': { 'tools.dataset': { 'tools.dataset.get_antibiotics': ('dataset.html#get_antibiotics', 'tools/dataset.py'),
                               'tools.dataset.get_g12d': ('dataset.html#get_g12d', 'tools/dataset.py')},
            'tools.esm': {'tools.esm.esm_embeddings': ('esm.html#esm_embeddings', 'tools/esm.py')},
            'tools.feature': { 'tools.feature.smi2morgan': ('feature.html#smi2morgan', 'tools/feature.py'),
                               'tools.feature.smi2prop': ('feature.html#smi2prop', 'tools/feature.py')},
            'tools.plot': { 'tools.plot.get_embedding': ('plot.html#get_embedding', 'tools/plot.py'),
                            'tools.plot.plot_embedding': ('plot.html#plot_embedding', 'tools/plot.py')}}}
