# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_func2.ipynb.

# %% auto 0
__all__ = ['myadd2']

# %% ../nbs/01_func2.ipynb 4
from .func import *

# %% ../nbs/01_func2.ipynb 5
def myadd2(a,b):
    return myadd(a,b)
