# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_plot.ipynb.

# %% auto 0
__all__ = ['get_pca', 'smi2morgan']

# %% ../nbs/01_plot.ipynb 3
from sklearn.decomposition import PCA
from fastbook import *

# %% ../nbs/01_plot.ipynb 6
def get_pca(df,# the first column is name/id
           seed=123
           ):
    pca = PCA(n_components=2, random_state = seed)
    proj = pca.fit_transform(df.iloc[:,1:])
    t = pd.DataFrame(proj, columns=["PCA1", "PCA2"])
    t['ID']=df.columns[0]
    return t

# %% ../nbs/01_plot.ipynb 10
def smi2morgan(df,
               smi_colname = "SMILES",
               id_colname = "ID"
              ):
    mols = [Chem.MolFromSmiles(smi) for smi in df[smi_colname]]
    morgan_fps = [AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=2048) for mol in mols]
    fp_df = pd.DataFrame(np.array(morgan_fps), index=df[id_colname])
    colnames = [f'morgan_{i}' for i in fp_df.columns]
    fp_df.columns = colnames
    fp_df = fp_df.reset_index()
    return fp_df
